services:
  node:
    image: node:19-alpine
    working_dir: /usr/app
    volumes:
    - .:/usr/app
    command: "yarn run watch"
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 2G
