= Les logs

[NOTE.speaker]
====
* Les logs :
* Si on limite les accès disques
* qu'on souhaite éviter que TOUS les logs sortent sur la sortie standard
* comment faire pour les gérer correctement ?
====


== R16 : Exporter les journaux avec Docker

[NOTE.speaker]
====
* "Le service Docker doit être conﬁguré pour collecter les journaux d’évènements issus de l’application « conteneurisée » et les exporter vers un serveur centralisé avec l’option --log-driver=<logging driver> (en ligne de commande ou dans le ﬁchier de conﬁguration)."
====

== R16- : Exporter les journaux depuis l'intérieur du conteneur

[NOTE.speaker]
====
* "L'export des journaux d’évènements issus de l'application « conteneurisée » peut être mise en œuvre à l’intérieur du conteneur par une solution distincte de Docker."
====

== Objectifs

* Dehors les logs !

[NOTE.speaker]
====
* On ne garde pas les logs sur la machine
* De manière générale, les logs doivent être centralisés sur une autre machine. Que ce soit pour des applications containerisées ou non.
====


