= Limitons notre consommation
:imagesdir: ../../src/images

[NOTE.speaker]
====
* Pour éviter que les containers consomment toutes les ressources disponibles
* Et mettent notre système à l'arrêt ou en mode dégradé.
* Problème de disponibilités
====

== R9
=== Dédier les Control groups pour chaque conteneur

[cols=2, grid=none]
|===
a|
[source, bash]
----
docker run busybox
----
a|
[source, yaml]
----
version: "2.7"
services:
  busybox:
    image: busybox
    #cgroup_parent: forbid
----
|===

[NOTE.speaker]
====
* "Chaque conteneur doit être démarré avec des Control Groups distincts de l’hôte et donc sans l’option --cgroup-parent."

Les cgroups : fonctionnalité du noyau Linux pour limiter, compter et isoler l'utilisation des ressources (processeur, mémoire, utilisation disque, etc.). Les groupes de controle permettent de créer des restrictions.
Par défaut Docker crée des control group pour chaque container, laissez comme ça.
====

== R10
=== Limiter l'utilisation de la mémoire de l'hôte pour chaque conteneur

[cols=2, grid=none]
|===
a|
[source, bash]
----
docker run \
  --memory=128m \
  --memory-swap=64m busybox
----
a|
[source, yaml]
----
version: "2.7"
services:
  busybox:
    image: busybox
    mem_limit: 128m
    memswap_limit: 64m
----
|===

[NOTE.speaker]
====
* "Chaque conteneur doit être démarré avec une limite maximale d’utilisation de la mémoire de l’hôte, avec l’option --memory, et une limite maximale d’utilisation de la mémoire SWAP de l’hôte avec l’option --memory-swap."

Par défaut, un conteneur n’a pas de contraintes de ressources et peut utiliser toutes les ressources disponibles sur l’hôte
====

== R11
=== Limiter l'utilisation du CPU de l'hôte pour chaque conteneur

[cols=2, grid=none]
|===
a|
[source, bash]
----
docker run --cpus=2 busybox
----
a|
[source, yaml]
----
version: "2.7"
services:
  busybox:
    image: busybox
    mem_limit: 128m
    memswap_limit: 64m
    cpu_percent: 80
    cpus: 2
----
|===



[NOTE.speaker]
====
* "Chaque conteneur doit être démarré avec une limite maximale d’utilisation du CPU de l’hôte avec l’option --cpus, ou avec les options --cpu-period et --cpu-quota."

cpu_count, cpu_percent, cpu_shares, cpu_period, cpu_quota, cpus, cpuset
====

== Objectifs

* Eviter la surcharge du système

[NOTE.speaker]
====
Via :

* Limitation mémoire
* Limitation CPU

Le petit plus, ça peut aider en écoconception aussi
====

== Bon à savoir

* Ce sont des configurations limitatives, non reservatives
* Docker-compose : attention à la version 3, utilisez la version 2

[NOTE.speaker]
====
* Vous pouvez donc dépasser les ressources de votre hôte que ce soit avec un ou plusieurs containers.
* Attention à ce que tous les containers ne tournent pas à "fond" tous en même temps.
* Même principe que l'Overprovisionning

* Bien que cela soit étrange
* La version 3 de docker-compose n'est pas l'évolution de la version 2
* Mais la version faite pour docker-swarm.
* Vous ne pourrez pas configurer les restrictions de ressources "docker" avec la version 3 de docker-compose en mode standalone.
* Restez sur la version 2 en mode standalone
====
