= Les limitations Kernel et autres joyeusetés

[NOTE.speaker]
====
* Le boss mode
* Capabilities Kernel, namespace PID, IPC, etc., autant d'éléments de configuration permettant de vraiment isoler docker du reste du système.
====

== Révisions
=== Les namespaces système

* Fonctionnalité du noyau linux :
** Partitionnement des ressources
** Limitation des accès au namespace du groupe de process d'un même namespace

[NOTE.speaker]
====
* Les espaces de noms sont une fonctionnalité du noyau Linux qui partitionne les ressources du noyau de telle sorte qu'un ensemble de processus voit un ensemble de ressources tandis qu'un autre ensemble de processus voit un ensemble différent de ressources.
====

== Révisions
=== Les namespaces dédiées à chaque container

* MNT : point de montage du FS
* PID : id des process
* NET : interface réseau
* IPC : canaux de communcation inter-prcess
* UTS : hostname, résolution de nom de domaine NIS

[NOTE.speaker]
====
* Quelques namespaces sont spécifiques à chaque container

====

== Révisions
=== Les namespaces partagés avec l'hôte

* USER ID : partage des id user
* CGROUP : règles d'accès aux ressources
* Time : partage de l'heure avec l'hôte

[NOTE.speaker]
====
* D'autre sont partagé avec l'host
* Le plus classique les id user, on s'est tous rendu compte des bizzareries quand on fait des montages sur le disque
* Le namespage des CGroup, comme on en a parlé un peu avant

====

[.background-easy]
== R6
=== Dédier des namespaces PID, IPC et UTS pour chaque conteneur

[source, bash]
----
docker run --pid= --uts= ... busybox # INTERDIT !
----

[NOTE.speaker]
====
"Chaque conteneur doit être démarré avec les namespaces PID, IPC et UTS distincts de l’hôte et des autres conteneurs et donc sans les options --pid, --ipc et --uts."

* Il est déconseillé d'essayer d'utiliser les namespace host dans les containers.
* Typiquement, on pourrait kill des process host à partir d'un container
* Ou faire communiquer des process interne au container avec d'autres process de l'hote
* Et vous ne voulez pas ça !
====

[.background-hard]
== R7
=== Dédier un namespace USER ID pour chaque conteneur

[source, bash]
----
#/ etc/systemd/system/docker.service.d/override.conf
ExecStart=/usr/bin/dockerd ... --userns-remap="secureuser:secureuser"
----

[NOTE.speaker]
====
* "Le service Docker doit être conﬁguré pour démarrer tous les conteneurs avec un namespace USER ID distinct de l’hôte et des autres conteneurs avec l’option --userns-remap (en ligne de commande ou dans le ﬁchier de conﬁguration). Cette conﬁguration doit s’accompagner d’une interdiction de créer de nouveau namespace USER ID à l’intérieur du conteneur."
* ATTENTION avec les bind mounts et les permissions
* les id de l'utilisateur dans le container ne seront plus les mêmes que sur l'host
* "on map ses ids sur un autre".
====

[.background-hard]
== R7+
=== Restreindre la création des Namespace USER ID à l'utilisateur root

[NOTE.speaker]
====
* "Sur les systèmes Linux à base Debian, la conﬁguration système kernel.unprivileged_userns_clone doit être égale à 0 (valeur par défaut) pour restreindre la création d’un Namespace USER ID au seul utilisateur root (UID=0)."
* On touche pas non plus, sinon vous allez permettre aux utilisateurs non root de créer des espace de nom. Et vous ne le voulez, c'est sur !
====

[.background-medium]
== R7-
=== Restreindre le partage du Namespace USER ID de l'hôte

[source, bash]
----
docker run --userns=host busybox
----

[NOTE.speaker]
====
* Si vous avez fait un remap MAIS que vous avez besoin de mapper sur les uid des utilisateurs de l'host
* "Lorsqu’un conteneur doit être démarré en partageant le namespace USER ID avec celui de l’hôte, et que le service Docker est configuré pour démarrer tous les conteneurs avec un namespace USER ID distinct de celui de l’hôte, il est possible d’utiliser l’option --userns=host au démarrage du conteneur. Dans ce cas, la menace de compromission de l’utilisateur root (UID=0) de l’hôte par le conteneur est à considérer."
====

== Révision
=== Les capabilities Kernel

* "Privilèges" que donne le noyau donne à des programmes

== Révision
=== Les capabilities offertes aux containers

[.capabilities-table, cols=2, grid=none, frame=none]
|===
a|
* CAP_AUDIT_WRITE
* CAP_CHOWN
* CAP_DAC_OVERRIDE
* CAP_FOWNER
* CAP_FSETID
* CAP_KILL
* CAP_NET_BIND_SERVICE
a|
* CAP_NET_RAW
* CAP_MKNOD
* CAP_SETFCAP
* CAP_SETPCAP
* CAP_SETUID
* CAP_SETGID
* CAP_SYS_CHROOT
|===



[.background-hard]
== R8
=== Interdire l'utilisation des capabilities


[cols=2, grid=none, frame=none]
|===
a|
[source, bash]
----
docker run --cap-drop=ALL busybox
----
a|
[source, yaml]
----
services:
  busybox:
    image: busybox
    cap_drop:
      - ALL
----
|===

[NOTE.speaker]
====
* "Chaque conteneur doit être démarré sans aucune capability avec l’option --cap-drop=ALL"
* Sur des outils que vous ne maitrisez pas, c'est risqué (genre gitlab)
====

[.background-hard]
== R8-
=== Limiter l'utilisation des capabilities

[grid=none, frame=none]
|===
a|
[source, bash]
----
docker run --cap-drop=ALL --cap-add=CHOWN busybox
----
a|
[source, yaml]
----
services:
  busybox:
    image: busybox
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
----
|===

[NOTE.speaker]
====
* "Un conteneur peut être démarré avec les capabilities strictement nécessaires, non sensibles, avec les options --cap-drop=ALL et --cap-add={”capability A”}."
* Next slide
====

== Die and retry

[NOTE.speaker]
====
* Et là, c'est Die and retry
* Il n'y a pas, aujourd'hui, de recette magique pour trouver les bonnes capabilities. Il faut tester si le service fonctionne et rajouter des capabilities jusqu'à ce que ce soit ok.
====

== Objectif

* Restreindre au maximum les interactions que les containers peuvent avoir avec le système

[NOTE.speaker]
====
* On limite les actions que les containers peuvent faire
====
